name: CICD

on: 
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      # Copy of the repository’s source code
      - uses: actions/checkout@v4
      # Setup Go
      - name: Setup Go  
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      # Install lint
      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint
      # Run vet and lint
      - name: Run vet & lint
        run: |
          go vet .
          golint .

